name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        environment-file: environment.yml
        activate-environment: myenv  # 환경 이름을 "base"가 아닌 다른 것으로 설정

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda activate myenv
        conda env update --file environment.yml --prune
        conda list

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        conda activate myenv
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        conda activate myenv
        pytest
